/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cliente;

import Cliente.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author Senac
 */
public class FormCliente extends javax.swing.JFrame {

    /**
     * Creates new form FormCliente
     */
    public FormCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LbTelefone = new javax.swing.JLabel();
        TxtFProfissao = new javax.swing.JTextField();
        TxtFTelefone = new javax.swing.JTextField();
        LbEmail = new javax.swing.JLabel();
        TxtFEmail = new javax.swing.JTextField();
        LbDataNascimento = new javax.swing.JLabel();
        LbNome = new javax.swing.JLabel();
        TxtFDataNascimento = new javax.swing.JTextField();
        TxtFNome = new javax.swing.JTextField();
        LbSexo = new javax.swing.JLabel();
        LbCPF = new javax.swing.JLabel();
        TxtFSexo = new javax.swing.JTextField();
        TxtFCPF = new javax.swing.JTextField();
        LbEstadoCivil = new javax.swing.JLabel();
        LbEndereco = new javax.swing.JLabel();
        TxtFEstadoCivil = new javax.swing.JTextField();
        TxtFEndereco = new javax.swing.JTextField();
        LbProfissao = new javax.swing.JLabel();
        BtnLimpar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        lbCodigoCliente = new javax.swing.JLabel();
        txtfCodigoCliente = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMRelatorio = new javax.swing.JMenu();
        jMIRelatorio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        LbTelefone.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbTelefone.setText("Telefone:");

        LbEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbEmail.setText("Email:");

        LbDataNascimento.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbDataNascimento.setText("Data Nascimento:");

        LbNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbNome.setText("Nome Completo:");

        LbSexo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbSexo.setText("Sexo:");

        LbCPF.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbCPF.setText("CPF:");

        LbEstadoCivil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbEstadoCivil.setText("Estado Civil:");

        LbEndereco.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbEndereco.setText("Endereço:");

        LbProfissao.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbProfissao.setText("Profissão:");

        BtnLimpar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BtnLimpar.setText("LIMPAR");
        BtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparActionPerformed(evt);
            }
        });

        btnMostrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnGravar.setText("GRAVAR");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        lbCodigoCliente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbCodigoCliente.setText("Código");

        btnAtualizar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(LbEstadoCivil)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtFEstadoCivil))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lbCodigoCliente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(LbDataNascimento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtFDataNascimento))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(LbEndereco)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(LbEmail)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtFEmail)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LbNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(LbProfissao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LbTelefone)
                            .addComponent(LbCPF)
                            .addComponent(LbSexo))
                        .addGap(12, 12, 12)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtFCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(TxtFTelefone)
                    .addComponent(TxtFSexo)
                    .addComponent(TxtFProfissao))
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGravar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCodigoCliente)
                    .addComponent(txtfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbCPF)
                    .addComponent(TxtFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbEndereco)
                    .addComponent(TxtFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbTelefone)
                    .addComponent(TxtFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbEmail)
                    .addComponent(TxtFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbSexo)
                    .addComponent(TxtFSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDataNascimento)
                    .addComponent(TxtFDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbProfissao)
                    .addComponent(TxtFProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbEstadoCivil)
                    .addComponent(TxtFEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnMostrar)
                    .addComponent(BtnLimpar)
                    .addComponent(btnExcluir))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jMRelatorio.setText("Relatório");

        jMIRelatorio.setText("Dados");
        jMIRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRelatorioActionPerformed(evt);
            }
        });
        jMRelatorio.add(jMIRelatorio);

        jMenuBar1.add(jMRelatorio);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        Limpar();
    }//GEN-LAST:event_BtnLimparActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        Cliente c = this.MontarCliente();
        JOptionPane.showMessageDialog(null,"Nome: "+c.getNome()+"\nCPF: "+c.getCPF()+"\nEndereço: "+c.getEndereco()+
                "\nTelefone: "+c.getTelefone()+"\nEmail: "+c.getEmail()+"\nData Nascimento: "+c.getDataNascimento()+
                "\nSexo: "+c.getSexo()+"\nEstado Civil: "+c.getEstadoCivil()+"\nProfissão: "+c.getProfissao());
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        Cliente c = this.MontarCliente();
        if (c != null) {
            ClienteCtrl cc = new ClienteCtrl();
            cc.insert(c);            
        }else{
           JOptionPane.showMessageDialog(null, "Preencha todos os campos corretamente.", "Erro", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_btnGravarActionPerformed
    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        Cliente c = this.MontarCliente();
        if (c != null && !txtfCodigoCliente.getText().trim().isEmpty()) {
            c.setCodCliente(Integer.parseInt(txtfCodigoCliente.getText()));
            ClienteCtrl cc = new ClienteCtrl();
            cc.update(c);            
        }else{
           JOptionPane.showMessageDialog(null, "Preencha todos os campos corretamente.", "Erro", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        ClienteCtrl cc = new ClienteCtrl();
        if(!txtfCodigoCliente.getText().trim().isEmpty()){
            int cod = Integer.parseInt(txtfCodigoCliente.getText());
            cc.delete(cod);
        }else{
            JOptionPane.showMessageDialog(null,"Preencha o campo.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jMIRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRelatorioActionPerformed
        ClienteCtrl cc = new ClienteCtrl();
        cc.SelectAll();
    }//GEN-LAST:event_jMIRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public void CadastroCliente() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCliente().setVisible(true);
            }
        });
    }
    
    public Cliente MontarCliente(){
        if (TxtFNome.getText().trim().isEmpty() || TxtFCPF.getText().trim().isEmpty() 
                || TxtFEndereco.getText().trim().isEmpty() || TxtFTelefone.getText().trim().isEmpty() 
                || TxtFTelefone.getText().trim().isEmpty() || TxtFEmail.getText().trim().isEmpty() 
                || TxtFDataNascimento.getText().trim().isEmpty() || TxtFSexo.getText().trim().isEmpty() 
                || TxtFEstadoCivil.getText().trim().isEmpty() || TxtFProfissao.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Por favor, preencha todos os campos.","Erro",JOptionPane.ERROR_MESSAGE);
            return null;
        }
        try{
            Cliente c = new Cliente();
            c.setNome(TxtFNome.getText());
            c.setCPF(Long.parseLong(TxtFCPF.getText()));
            c.setEndereco(TxtFEndereco.getText());
            c.setTelefone(Long.parseLong(TxtFTelefone.getText()));
            c.setEmail(TxtFEmail.getText());
            c.setDataNascimento(TxtFDataNascimento.getText());
            c.setSexo(TxtFSexo.getText());
            c.setEstadoCivil(TxtFEstadoCivil.getText());
            c.setProfissao(TxtFProfissao.getText());
            return c;            
        }catch (NumberFormatException n) {
            JOptionPane.showMessageDialog(null, "Deve ser um número.", "Erro", JOptionPane.ERROR_MESSAGE);
            return null; 
        }
    }
    
    public void Limpar(){
        txtfCodigoCliente.setText("");
        TxtFCPF.setText("");
        TxtFDataNascimento.setText("");
        TxtFEmail.setText("");
        TxtFEndereco.setText("");
        TxtFEstadoCivil.setText("");
        TxtFNome.setText("");
        TxtFProfissao.setText("");
        TxtFSexo.setText("");
        TxtFTelefone.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JLabel LbCPF;
    private javax.swing.JLabel LbDataNascimento;
    private javax.swing.JLabel LbEmail;
    private javax.swing.JLabel LbEndereco;
    private javax.swing.JLabel LbEstadoCivil;
    private javax.swing.JLabel LbNome;
    private javax.swing.JLabel LbProfissao;
    private javax.swing.JLabel LbSexo;
    private javax.swing.JLabel LbTelefone;
    private javax.swing.JTextField TxtFCPF;
    private javax.swing.JTextField TxtFDataNascimento;
    private javax.swing.JTextField TxtFEmail;
    private javax.swing.JTextField TxtFEndereco;
    private javax.swing.JTextField TxtFEstadoCivil;
    private javax.swing.JTextField TxtFNome;
    private javax.swing.JTextField TxtFProfissao;
    private javax.swing.JTextField TxtFSexo;
    private javax.swing.JTextField TxtFTelefone;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JMenuItem jMIRelatorio;
    private javax.swing.JMenu jMRelatorio;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCodigoCliente;
    private javax.swing.JTextField txtfCodigoCliente;
    // End of variables declaration//GEN-END:variables
}
