package Veiculo;

import javax.swing.JOptionPane;

public class FormVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form FormVeiculo
     */
    public FormVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LbPlaca = new javax.swing.JLabel();
        TxtfPlaca = new javax.swing.JTextField();
        LbMarca = new javax.swing.JLabel();
        TxtfMarca = new javax.swing.JTextField();
        LbModelo = new javax.swing.JLabel();
        TxtfModelo = new javax.swing.JTextField();
        LbAnoPub = new javax.swing.JLabel();
        TxtfAnoPub = new javax.swing.JTextField();
        LbCor = new javax.swing.JLabel();
        TxtfCor = new javax.swing.JTextField();
        LbTipo = new javax.swing.JLabel();
        TxtfTipo = new javax.swing.JTextField();
        LbChassi = new javax.swing.JLabel();
        TxtfChassi = new javax.swing.JTextField();
        LbKM = new javax.swing.JLabel();
        TxtfKM = new javax.swing.JTextField();
        LbData = new javax.swing.JLabel();
        TxtfData = new javax.swing.JTextField();
        BtnLimpar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        lbCodigoVeiculo = new javax.swing.JLabel();
        txtfCodigoVeiculo = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmRelatorio = new javax.swing.JMenu();
        jmiDados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        LbPlaca.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbPlaca.setText("Placa Veículo:");

        LbMarca.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbMarca.setText("Marca:");

        LbModelo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbModelo.setText("Modelo:");

        LbAnoPub.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbAnoPub.setText("Ano Fabricação:");

        LbCor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbCor.setText("Cor:");

        LbTipo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbTipo.setText("Tipo Combustível:");

        LbChassi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbChassi.setText("Número Chassi:");

        LbKM.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbKM.setText("KM:");

        LbData.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbData.setText("Data última revisão:");

        BtnLimpar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BtnLimpar.setText("LIMPAR");
        BtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparActionPerformed(evt);
            }
        });

        btnMostrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnGravar.setText("GRAVAR");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        lbCodigoVeiculo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbCodigoVeiculo.setText("Código:");

        btnAtualizar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCodigoVeiculo)
                    .addComponent(LbPlaca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfCodigoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LbData)
                        .addGap(18, 18, 18)
                        .addComponent(TxtfData))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LbChassi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtfChassi))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LbTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtfTipo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LbMarca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LbAnoPub)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtfAnoPub, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LbModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtfModelo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LbCor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtfCor))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LbKM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtfKM)))))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoVeiculo)
                    .addComponent(txtfCodigoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbPlaca)
                    .addComponent(TxtfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbMarca)
                    .addComponent(TxtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbModelo)
                    .addComponent(TxtfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbAnoPub)
                    .addComponent(TxtfAnoPub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbCor)
                    .addComponent(TxtfCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbTipo)
                    .addComponent(TxtfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbKM)
                    .addComponent(TxtfKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbChassi)
                    .addComponent(TxtfChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbData)
                    .addComponent(TxtfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLimpar)
                    .addComponent(btnMostrar)
                    .addComponent(btnGravar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnExcluir))
                .addGap(30, 30, 30))
        );

        jmRelatorio.setText("Relatório");

        jmiDados.setText("Dados");
        jmiDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDadosActionPerformed(evt);
            }
        });
        jmRelatorio.add(jmiDados);

        jMenuBar1.add(jmRelatorio);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        Limpar();
    }//GEN-LAST:event_BtnLimparActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        Veiculo v = this.MontarVeiculo();
        JOptionPane.showMessageDialog(null,"Placa veículo: "+v.getPlacaVeiculo()+"\nMarca: "+v.getMarca()+
                "\nModelo: "+v.getModelo()+"\nAno fabricação: "+v.getAnoFabricacao()+"\nCor: "+v.getCor()+
                "\nTipo combustível: "+v.getTipoCombustivel()+"\nNúmero chassi: "+v.getNumeroChassi()+
                "\nQuilometragem: "+v.getQuilometragem()+"\nData revisão: "+v.getDataRevisao());
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        Veiculo v = this.MontarVeiculo();
        if (v != null){
            VeiculoCtrl vc = new VeiculoCtrl();
            vc.insert(v);            
        }else{
            JOptionPane.showMessageDialog(null,"Favor preencher todos os campos.");
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
       Veiculo v = this.MontarVeiculo(); 
       if (v != null && !txtfCodigoVeiculo.getText().trim().isEmpty()){
           v.setCodVeiculo(Integer.parseInt(txtfCodigoVeiculo.getText()));
           VeiculoCtrl vc = new VeiculoCtrl();
           vc.update(v); 
       }else{
           JOptionPane.showMessageDialog(null,"Favor preencher todos os campos.");
       }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        VeiculoCtrl vc = new VeiculoCtrl();
        if (!txtfCodigoVeiculo.getText().trim().isEmpty()){
            int cod = Integer.parseInt(txtfCodigoVeiculo.getText());
            vc.delete(cod);
        }else{
            JOptionPane.showMessageDialog(null,"Preencha o campo.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jmiDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDadosActionPerformed
        VeiculoCtrl vc = new VeiculoCtrl();
        vc.SelectAll();
    }//GEN-LAST:event_jmiDadosActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public void CadastroVeiculo() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVeiculo().setVisible(true);
            }
        });
    }
    
    public Veiculo MontarVeiculo(){
        if (TxtfPlaca.getText().trim().isEmpty() || TxtfMarca.getText().trim().isEmpty()
                || TxtfModelo.getText().trim().isEmpty() || TxtfAnoPub.getText().trim().isEmpty()
                || TxtfCor.getText().trim().isEmpty() || TxtfTipo.getText().trim().isEmpty()
                || TxtfChassi.getText().trim().isEmpty() || TxtfKM.getText().trim().isEmpty()
                || TxtfData.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Favor preencher todos os campos.");
            return null;
        }
        try{
            Veiculo v = new Veiculo();
            v.setPlacaVeiculo(TxtfPlaca.getText());
            v.setMarca(TxtfMarca.getText());
            v.setModelo(TxtfModelo.getText());
            v.setAnoFabricacao(Integer.parseInt(TxtfAnoPub.getText()));
            v.setCor(TxtfCor.getText());
            v.setTipoCombustivel(TxtfTipo.getText());
            v.setNumeroChassi(Integer.parseInt(TxtfChassi.getText()));
            v.setQuilometragem(Float.parseFloat(TxtfKM.getText()));
            v.setDataRevisao(TxtfData.getText());
            return v;
        }catch(NumberFormatException n){
            JOptionPane.showMessageDialog(null,n,"Error",JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
    
    public void Limpar(){
        txtfCodigoVeiculo.setText("");
        TxtfAnoPub.setText("");
        TxtfChassi.setText("");
        TxtfCor.setText("");
        TxtfData.setText("");
        TxtfKM.setText("");
        TxtfMarca.setText("");
        TxtfModelo.setText("");
        TxtfPlaca.setText("");
        TxtfTipo.setText("");        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JLabel LbAnoPub;
    private javax.swing.JLabel LbChassi;
    private javax.swing.JLabel LbCor;
    private javax.swing.JLabel LbData;
    private javax.swing.JLabel LbKM;
    private javax.swing.JLabel LbMarca;
    private javax.swing.JLabel LbModelo;
    private javax.swing.JLabel LbPlaca;
    private javax.swing.JLabel LbTipo;
    private javax.swing.JTextField TxtfAnoPub;
    private javax.swing.JTextField TxtfChassi;
    private javax.swing.JTextField TxtfCor;
    private javax.swing.JTextField TxtfData;
    private javax.swing.JTextField TxtfKM;
    private javax.swing.JTextField TxtfMarca;
    private javax.swing.JTextField TxtfModelo;
    private javax.swing.JTextField TxtfPlaca;
    private javax.swing.JTextField TxtfTipo;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmRelatorio;
    private javax.swing.JMenuItem jmiDados;
    private javax.swing.JLabel lbCodigoVeiculo;
    private javax.swing.JTextField txtfCodigoVeiculo;
    // End of variables declaration//GEN-END:variables
}
