/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Livros;

import Livros.Livros;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus
 */
public class FormLivros extends javax.swing.JFrame {

    /**
     * Creates new form FormLivros
     */
    public FormLivros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        LbTitulo = new javax.swing.JLabel();
        TxtfTitulo = new javax.swing.JTextField();
        LbAutor = new javax.swing.JLabel();
        TxtfAutor = new javax.swing.JTextField();
        LbISBN = new javax.swing.JLabel();
        TxtfISBN = new javax.swing.JTextField();
        LbEditora = new javax.swing.JLabel();
        TxtfEditora = new javax.swing.JTextField();
        LbAnoPub = new javax.swing.JLabel();
        TxtfAnoPub = new javax.swing.JTextField();
        LbGenero = new javax.swing.JLabel();
        TxtfGenero = new javax.swing.JTextField();
        LbNumPag = new javax.swing.JLabel();
        TxtfNumPag = new javax.swing.JTextField();
        LbIdioma = new javax.swing.JLabel();
        TxtfIdioma = new javax.swing.JTextField();
        LbLocBibli = new javax.swing.JLabel();
        TxtfLocBibli = new javax.swing.JTextField();
        BtnLimpar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        lbCodigoLivro = new javax.swing.JLabel();
        txtfCodigoLivro = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmRelatorio = new javax.swing.JMenu();
        jmiDados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jRadioButton1.setText("jRadioButton1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        LbTitulo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbTitulo.setText("Titulo:");

        LbAutor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbAutor.setText("Autor:");

        LbISBN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbISBN.setText("ISBN:");

        LbEditora.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbEditora.setText("Editora:");

        LbAnoPub.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbAnoPub.setText("Ano Publicação:");

        LbGenero.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbGenero.setText("Gênero:");

        LbNumPag.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbNumPag.setText("Número de páginas:");

        LbIdioma.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbIdioma.setText("Idioma:");

        LbLocBibli.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbLocBibli.setText("Localização na Biblioteca:");

        BtnLimpar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BtnLimpar.setText("LIMPAR");
        BtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparActionPerformed(evt);
            }
        });

        btnMostrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnGravar.setText("GRAVAR");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        lbCodigoLivro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbCodigoLivro.setText("Código:");

        btnAtualizar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LbLocBibli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtfLocBibli))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnGravar)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnLimpar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(LbGenero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtfGenero))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(LbEditora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtfEditora))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LbTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LbAutor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbCodigoLivro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfCodigoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LbIdioma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtfIdioma))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LbISBN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtfISBN))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LbAnoPub)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtfAnoPub))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LbNumPag)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtfNumPag)))))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoLivro)
                    .addComponent(txtfCodigoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbTitulo)
                    .addComponent(TxtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbISBN)
                    .addComponent(TxtfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbAutor)
                    .addComponent(TxtfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbAnoPub)
                    .addComponent(TxtfAnoPub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbEditora)
                    .addComponent(TxtfEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbNumPag)
                    .addComponent(TxtfNumPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbGenero)
                    .addComponent(TxtfGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbIdioma)
                    .addComponent(TxtfIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbLocBibli)
                    .addComponent(TxtfLocBibli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLimpar)
                    .addComponent(btnMostrar)
                    .addComponent(btnGravar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnExcluir))
                .addGap(25, 25, 25))
        );

        jmRelatorio.setText("Relatório");

        jmiDados.setText("Dados");
        jmiDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDadosActionPerformed(evt);
            }
        });
        jmRelatorio.add(jmiDados);

        jMenuBar1.add(jmRelatorio);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        Limpar();
    }//GEN-LAST:event_BtnLimparActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        Livros l = this.MontarLivros();
        JOptionPane.showMessageDialog(null,"Título: "+l.getTitulo()+"\nAutor: "+l.getAutor()+"\nISBN: "+l.getISBN()+
                "\nEditora: "+l.getEditora()+"\nAno de publicação: "+l.getAnoPub()+
                "\nGênero: "+l.getGenero()+"\nNúmero de páginas: "+l.getNumPag()+
                "\nIdioma: "+l.getIdioma()+"\nLocalização na biblioteca: "+l.getLocBiblioteca());
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        Livros l = this.MontarLivros();
        if (l != null){
            LivrosCtrl lc = new LivrosCtrl();
            lc.insert(l);
        }else{
            JOptionPane.showMessageDialog(null,"Favor preencher todos os campos.");
        }    
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        Livros l = this.MontarLivros();
        if (l != null && !txtfCodigoLivro.getText().trim().isEmpty()){
            l.setCodLivros(Integer.parseInt(txtfCodigoLivro.getText()));
            LivrosCtrl lc = new LivrosCtrl();
            lc.update(l);
        }else{
            JOptionPane.showMessageDialog(null,"Favor preencher todos os campos.");
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        LivrosCtrl lc = new LivrosCtrl();
        if (!txtfCodigoLivro.getText().trim().isEmpty()){
            int cod = Integer.parseInt(txtfCodigoLivro.getText());
            lc.delete(cod);
        }else{
            JOptionPane.showMessageDialog(null,"Preencha o campo.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jmiDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDadosActionPerformed
        LivrosCtrl lc = new LivrosCtrl();
        lc.SelectAll();
    }//GEN-LAST:event_jmiDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public void CadastroLivros() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLivros().setVisible(true);
            }
        });
    }
    
    public Livros MontarLivros(){
        if (TxtfTitulo.getText().trim().isEmpty() || TxtfAutor.getText().trim().isEmpty()
                || TxtfISBN.getText().trim().isEmpty() || TxtfEditora.getText().trim().isEmpty()
                || TxtfAnoPub.getText().trim().isEmpty() || TxtfGenero.getText().trim().isEmpty()
                || TxtfNumPag.getText().trim().isEmpty() || TxtfIdioma.getText().trim().isEmpty()
                || TxtfLocBibli.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Favor preencher todos os campos.");
            return null;
        }
        try{
            Livros l = new Livros();
            l.setTitulo(TxtfTitulo.getText());
            l.setAutor(TxtfAutor.getText());
            l.setISBN(Long.parseLong(TxtfISBN.getText()));
            l.setEditora(TxtfEditora.getText());
            l.setAnoPub(TxtfAnoPub.getText());
            l.setGenero(TxtfGenero.getText());
            l.setNumPag(Integer.parseInt(TxtfNumPag.getText()));
            l.setIdioma(TxtfIdioma.getText());
            l.setLocBiblioteca(TxtfLocBibli.getText());
            return l;
        }catch(NumberFormatException n){
            JOptionPane.showMessageDialog(null,n,"Error",JOptionPane.ERROR_MESSAGE);
            return null;
        }    
    }
    
    
    public void Limpar(){
        txtfCodigoLivro.setText("");
        TxtfAnoPub.setText("");
        TxtfAutor.setText("");
        TxtfEditora.setText("");
        TxtfGenero.setText("");
        TxtfISBN.setText("");
        TxtfIdioma.setText("");
        TxtfLocBibli.setText("");
        TxtfNumPag.setText("");
        TxtfTitulo.setText("");        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JLabel LbAnoPub;
    private javax.swing.JLabel LbAutor;
    private javax.swing.JLabel LbEditora;
    private javax.swing.JLabel LbGenero;
    private javax.swing.JLabel LbISBN;
    private javax.swing.JLabel LbIdioma;
    private javax.swing.JLabel LbLocBibli;
    private javax.swing.JLabel LbNumPag;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JTextField TxtfAnoPub;
    private javax.swing.JTextField TxtfAutor;
    private javax.swing.JTextField TxtfEditora;
    private javax.swing.JTextField TxtfGenero;
    private javax.swing.JTextField TxtfISBN;
    private javax.swing.JTextField TxtfIdioma;
    private javax.swing.JTextField TxtfLocBibli;
    private javax.swing.JTextField TxtfNumPag;
    private javax.swing.JTextField TxtfTitulo;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JMenu jmRelatorio;
    private javax.swing.JMenuItem jmiDados;
    private javax.swing.JLabel lbCodigoLivro;
    private javax.swing.JTextField txtfCodigoLivro;
    // End of variables declaration//GEN-END:variables
}
