/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Produtos;

import Produtos.Produtos;
import javax.swing.JOptionPane;

/**
 *
 * @author Senac
 */
public class FormProduto extends javax.swing.JFrame {

    /**
     * Creates new form FormProduto
     */
    public FormProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbNomeProduto = new javax.swing.JLabel();
        TxtfNomeProduto = new javax.swing.JTextField();
        LbCodProduto = new javax.swing.JLabel();
        TxtfCodigoProduto = new javax.swing.JTextField();
        LbDescricao = new javax.swing.JLabel();
        TxtfDescricao = new javax.swing.JTextField();
        LbPreco = new javax.swing.JLabel();
        TxtfPreco = new javax.swing.JTextField();
        LbQuantEstoq = new javax.swing.JLabel();
        TxtfQuantEstoque = new javax.swing.JTextField();
        LbCategoria = new javax.swing.JLabel();
        TxtfCategoria = new javax.swing.JTextField();
        LbDataValid = new javax.swing.JLabel();
        TxtfDataValid = new javax.swing.JTextField();
        LbFornecedor = new javax.swing.JLabel();
        TxtfFornecedor = new javax.swing.JTextField();
        LbLocEstoque = new javax.swing.JLabel();
        TxtfLocEstoque = new javax.swing.JTextField();
        BtnLimpar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        lbCodigoProduto = new javax.swing.JLabel();
        txtfCodProduto = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmRelatorio = new javax.swing.JMenu();
        jmiDados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel5.setText("jLabel1");

        jTextField5.setText("jTextField1");

        jLabel6.setText("jLabel1");

        jTextField6.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lbNomeProduto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbNomeProduto.setText("Nome:");

        LbCodProduto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbCodProduto.setText("Código do Produto:");

        LbDescricao.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbDescricao.setText("Descrição:");

        LbPreco.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbPreco.setText("Preço:");

        LbQuantEstoq.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbQuantEstoq.setText("Quantidade Estoque:");

        LbCategoria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbCategoria.setText("Categoria:");

        LbDataValid.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbDataValid.setText("Data Validade:");

        LbFornecedor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbFornecedor.setText("Fornecedor:");

        LbLocEstoque.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbLocEstoque.setText("Localização no Estoque:");

        BtnLimpar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BtnLimpar.setText("LIMPAR");
        BtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparActionPerformed(evt);
            }
        });

        btnMostrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnGravar.setText("GRAVAR");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        lbCodigoProduto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbCodigoProduto.setText("Código:");

        btnAtualizar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbCodigoProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LbQuantEstoq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtfQuantEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnAtualizar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnGravar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnMostrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BtnLimpar))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(LbPreco)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtfPreco))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(LbDescricao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtfDescricao))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbNomeProduto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtfNomeProduto))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(LbCodProduto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtfCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(LbLocEstoque)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TxtfLocEstoque))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(LbFornecedor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TxtfFornecedor))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(LbDataValid)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TxtfDataValid))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(LbCategoria)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TxtfCategoria)))
                            .addGap(23, 23, 23))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluir)
                .addGap(167, 167, 167))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoProduto)
                    .addComponent(txtfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeProduto)
                    .addComponent(TxtfNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbCodProduto)
                    .addComponent(TxtfCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDescricao)
                    .addComponent(TxtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbPreco)
                    .addComponent(TxtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbQuantEstoq)
                    .addComponent(TxtfQuantEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbCategoria)
                    .addComponent(TxtfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDataValid)
                    .addComponent(TxtfDataValid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbFornecedor)
                    .addComponent(TxtfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbLocEstoque)
                    .addComponent(TxtfLocEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLimpar)
                    .addComponent(btnMostrar)
                    .addComponent(btnGravar)
                    .addComponent(btnAtualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir)
                .addGap(15, 15, 15))
        );

        jmRelatorio.setText("Relatório");

        jmiDados.setText("Dados");
        jmiDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDadosActionPerformed(evt);
            }
        });
        jmRelatorio.add(jmiDados);

        jMenuBar1.add(jmRelatorio);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        Limpar();
    }//GEN-LAST:event_BtnLimparActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        Produtos p = this.MontarProduto();
        JOptionPane.showMessageDialog(null,"Nome: "+p.getNomeProduto()+"\nCódigo do produto: "+p.getCodigoProduto()+
                "\nDescrição: "+p.getDescricao()+"\nPreço: "+p.getPreco()+"\nQuantidade estoque: "+p.getQuantidadeEstoque()+
                "\nCategoria: "+p.getCategoria()+"\nData validade: "+p.getDataValidade()+"\nFornecedor: "+p.getFornecedor()+
                "\nLocal estoque: "+p.getLocEstoque());
        
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
       Produtos p = this.MontarProduto();
       if (p != null){
           ProdutosCtrl pc = new ProdutosCtrl();
           pc.insert(p);
       }else{
           JOptionPane.showMessageDialog(null,"Favor preencher todos os campos.");
       }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
       Produtos p = this.MontarProduto();
       if (p != null && !txtfCodProduto.getText().trim().isEmpty()){
           p.setCodProduto(Integer.parseInt(txtfCodProduto.getText()));
           ProdutosCtrl pc = new ProdutosCtrl();
           pc.update(p);
       }else{
           JOptionPane.showMessageDialog(null,"Favor preencher todos os campos.");
       } 
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        ProdutosCtrl pc = new ProdutosCtrl();
        if (!txtfCodProduto.getText().trim().isEmpty()){
            int cod = Integer.parseInt(txtfCodProduto.getText());
            pc.delete(cod);
        }else{
            JOptionPane.showMessageDialog(null,"Preencha o campo.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jmiDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDadosActionPerformed
        ProdutosCtrl pc = new ProdutosCtrl();
        pc.SelectAll();
    }//GEN-LAST:event_jmiDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public void CadastroProduto() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProduto().setVisible(true);
            }
        });
    }
    
    public Produtos MontarProduto(){
        if(TxtfNomeProduto.getText().trim().isEmpty() || TxtfCodigoProduto.getText().trim().isEmpty()
                || TxtfDescricao.getText().trim().isEmpty() || TxtfPreco.getText().trim().isEmpty()
                || TxtfQuantEstoque.getText().trim().isEmpty() || TxtfCategoria.getText().trim().isEmpty()
                || TxtfDataValid.getText().trim().isEmpty() || TxtfFornecedor.getText().trim().isEmpty()
                || TxtfLocEstoque.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Favor preencher todos os campos.");
            return null;
        }
        try{
            Produtos p = new Produtos();
            p.setNomeProduto(TxtfNomeProduto.getText());
            p.setCodigoProduto(TxtfCodigoProduto.getText());
            p.setDescricao(TxtfDescricao.getText());
            p.setPreco(Float.parseFloat(TxtfPreco.getText()));
            p.setQuantidadeEstoque(Float.parseFloat(TxtfQuantEstoque.getText()));
            p.setCategoria(TxtfCategoria.getText());
            p.setDataValidade(TxtfDataValid.getText());
            p.setFornecedor(TxtfFornecedor.getText());
            p.setLocEstoque(TxtfLocEstoque.getText());
            return p;
        }catch(NumberFormatException n){
            JOptionPane.showMessageDialog(null,n,"Error",JOptionPane.ERROR_MESSAGE);
            return null;
        }    
    }
    
    public void Limpar(){
        txtfCodProduto.setText("");
        TxtfCategoria.setText("");
        TxtfCodigoProduto.setText("");
        TxtfDataValid.setText("");
        TxtfDescricao.setText("");
        TxtfFornecedor.setText("");
        TxtfLocEstoque.setText("");
        TxtfNomeProduto.setText("");
        TxtfPreco.setText("");
        TxtfQuantEstoque.setText("");        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JLabel LbCategoria;
    private javax.swing.JLabel LbCodProduto;
    private javax.swing.JLabel LbDataValid;
    private javax.swing.JLabel LbDescricao;
    private javax.swing.JLabel LbFornecedor;
    private javax.swing.JLabel LbLocEstoque;
    private javax.swing.JLabel LbPreco;
    private javax.swing.JLabel LbQuantEstoq;
    private javax.swing.JTextField TxtfCategoria;
    private javax.swing.JTextField TxtfCodigoProduto;
    private javax.swing.JTextField TxtfDataValid;
    private javax.swing.JTextField TxtfDescricao;
    private javax.swing.JTextField TxtfFornecedor;
    private javax.swing.JTextField TxtfLocEstoque;
    private javax.swing.JTextField TxtfNomeProduto;
    private javax.swing.JTextField TxtfPreco;
    private javax.swing.JTextField TxtfQuantEstoque;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JMenu jmRelatorio;
    private javax.swing.JMenuItem jmiDados;
    private javax.swing.JLabel lbCodigoProduto;
    private javax.swing.JLabel lbNomeProduto;
    private javax.swing.JTextField txtfCodProduto;
    // End of variables declaration//GEN-END:variables
}
