/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ContasPagar;

import javax.swing.JOptionPane;

/**
 *
 * @author Matheus
 */
public class FormContasPagar extends javax.swing.JFrame {

    /**
     * Creates new form FormContasPagar
     */
    public FormContasPagar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        LbDesc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtaDesc = new javax.swing.JTextArea();
        LbPreco = new javax.swing.JLabel();
        TxtfPreco = new javax.swing.JTextField();
        LbDataNasc = new javax.swing.JLabel();
        TxtfDataVenc = new javax.swing.JTextField();
        LbDataPag = new javax.swing.JLabel();
        TxtfDataPag = new javax.swing.JTextField();
        LbFornecedor = new javax.swing.JLabel();
        TxtfFornecedor = new javax.swing.JTextField();
        LbCategoria = new javax.swing.JLabel();
        TxtfCategoria = new javax.swing.JTextField();
        LbStatus = new javax.swing.JLabel();
        TxtfStatus = new javax.swing.JTextField();
        LbMetodoPag = new javax.swing.JLabel();
        TxtfMetodoPag = new javax.swing.JTextField();
        LbObservacao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtaObservacao = new javax.swing.JTextArea();
        BtnLimpar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        lbCodigoContas = new javax.swing.JLabel();
        txtfCodigoConta = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMRelatorio = new javax.swing.JMenu();
        jMIDados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        LbDesc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbDesc.setText("Descrição da Conta:");

        TxtaDesc.setColumns(20);
        TxtaDesc.setRows(5);
        jScrollPane1.setViewportView(TxtaDesc);

        LbPreco.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbPreco.setText("Preço:");

        LbDataNasc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbDataNasc.setText("Data Vencimento:");

        LbDataPag.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbDataPag.setText("Data Pagamento:");

        LbFornecedor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbFornecedor.setText("Fornecedor:");

        LbCategoria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbCategoria.setText("Categoria:");

        LbStatus.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbStatus.setText("Status Pagamento:");

        LbMetodoPag.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbMetodoPag.setText("Método de Pagamento:");

        LbObservacao.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbObservacao.setText("Observação:");

        TxtaObservacao.setColumns(20);
        TxtaObservacao.setRows(5);
        jScrollPane2.setViewportView(TxtaObservacao);

        BtnLimpar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BtnLimpar.setText("LIMPAR");
        BtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparActionPerformed(evt);
            }
        });

        btnMostrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnGravar.setText("GRAVAR");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        lbCodigoContas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbCodigoContas.setText("Código:");

        btnAtualizar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("EXCLUIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbCodigoContas)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtfCodigoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LbObservacao)
                            .addComponent(LbDesc)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LbPreco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LbCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtfCategoria))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LbFornecedor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtfFornecedor))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(LbDataNasc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtfDataVenc, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LbDataPag)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtfDataPag, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LbStatus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtfStatus))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LbMetodoPag)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtfMetodoPag, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnLimpar)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoContas)
                    .addComponent(txtfCodigoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LbDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbPreco)
                    .addComponent(TxtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbCategoria)
                    .addComponent(TxtfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDataNasc)
                    .addComponent(TxtfDataVenc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbDataPag)
                    .addComponent(TxtfDataPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbFornecedor)
                    .addComponent(TxtfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbStatus)
                    .addComponent(TxtfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbMetodoPag)
                    .addComponent(TxtfMetodoPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LbObservacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLimpar)
                    .addComponent(btnMostrar)
                    .addComponent(btnGravar)
                    .addComponent(btnAtualizar)
                    .addComponent(jButton1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jMRelatorio.setText("Relatório");

        jMIDados.setText("Dados");
        jMIDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIDadosActionPerformed(evt);
            }
        });
        jMRelatorio.add(jMIDados);

        jMenuBar1.add(jMRelatorio);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        Limpar();
    }//GEN-LAST:event_BtnLimparActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        ContaPagar cp = this.MontarContaPagar();
        JOptionPane.showMessageDialog(null,"Descrição conta: "+cp.getDescricaoConta()+"\nPreço: "+cp.getPreco()+
                "\nData vencimento: "+cp.getDataVencimento()+"\nData pagamento: "+cp.getDataPagamento()+
                "\nFornecedor: "+cp.getFornecedor()+"\nCategoria: "+cp.getCategoria()+"\nStatus pagamento: "+cp.getStatusPag()+
                "\nMétodo pagamento: "+cp.getMetodoPag()+"\nObservação: "+cp.getObservacao());
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        ContaPagar cp = this.MontarContaPagar();
        if(cp != null){
            ContaPagarCtrl cpc = new ContaPagarCtrl();
            cpc.insert(cp);            
        }else{
            JOptionPane.showMessageDialog(null,"Favor preencher os campos corretamente.");
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        ContaPagar cp = this.MontarContaPagar();
        if(cp != null && !txtfCodigoConta.getText().trim().isEmpty()){
            cp.setCodContaPagar(Integer.parseInt(txtfCodigoConta.getText()));
            ContaPagarCtrl cpc = new ContaPagarCtrl();
            cpc.update(cp);
        }else{
            JOptionPane.showMessageDialog(null,"Favor preencher os campos corretamente.");            
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ContaPagarCtrl cpc = new ContaPagarCtrl();
        if (!txtfCodigoConta.getText().trim().isEmpty()){
            int cod = Integer.parseInt(txtfCodigoConta.getText());
            cpc.delete(cod);
        }else{
            JOptionPane.showMessageDialog(null,"Preencha o campo.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMIDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIDadosActionPerformed
        ContaPagarCtrl cpc = new ContaPagarCtrl();
        cpc.SelectAll();
    }//GEN-LAST:event_jMIDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public void CadastroContasPagar(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormContasPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormContasPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormContasPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormContasPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormContasPagar().setVisible(true);
            }
        });
    }
    
    public ContaPagar MontarContaPagar(){
        if (TxtaDesc.getText().trim().isEmpty() || TxtfPreco.getText().trim().isEmpty()
                || TxtfDataVenc.getText().trim().isEmpty() || TxtfDataPag.getText().trim().isEmpty()
                || TxtfFornecedor.getText().trim().isEmpty() || TxtfCategoria.getText().trim().isEmpty()
                || TxtfStatus.getText().trim().isEmpty() || TxtfMetodoPag.getText().trim().isEmpty()
                || TxtaObservacao.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Favor preencher os campos corretamente.");
            return null;
        }try{
            ContaPagar cp = new ContaPagar();
            cp.setDescricaoConta(TxtaDesc.getText());
            cp.setPreco(Float.parseFloat(TxtfPreco.getText()));
            cp.setDataVencimento(TxtfDataVenc.getText());
            cp.setDataPagamento(TxtfDataPag.getText());
            cp.setFornecedor(TxtfFornecedor.getText());
            cp.setCategoria(TxtfCategoria.getText());
            cp.setStatusPag(TxtfStatus.getText());
            cp.setMetodoPag(TxtfMetodoPag.getText());
            cp.setObservacao(TxtaObservacao.getText());
            return cp;            
        }catch(NumberFormatException n){
            JOptionPane.showMessageDialog(null,n,"Error",JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
    
    public void Limpar(){
        txtfCodigoConta.setText("");
        TxtaDesc.setText("");
        TxtaObservacao.setText("");
        TxtfCategoria.setText("");
        TxtfDataVenc.setText("");
        TxtfDataPag.setText("");
        TxtfFornecedor.setText("");
        TxtfMetodoPag.setText("");
        TxtfPreco.setText("");
        TxtfStatus.setText("");        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JLabel LbCategoria;
    private javax.swing.JLabel LbDataNasc;
    private javax.swing.JLabel LbDataPag;
    private javax.swing.JLabel LbDesc;
    private javax.swing.JLabel LbFornecedor;
    private javax.swing.JLabel LbMetodoPag;
    private javax.swing.JLabel LbObservacao;
    private javax.swing.JLabel LbPreco;
    private javax.swing.JLabel LbStatus;
    private javax.swing.JTextArea TxtaDesc;
    private javax.swing.JTextArea TxtaObservacao;
    private javax.swing.JTextField TxtfCategoria;
    private javax.swing.JTextField TxtfDataPag;
    private javax.swing.JTextField TxtfDataVenc;
    private javax.swing.JTextField TxtfFornecedor;
    private javax.swing.JTextField TxtfMetodoPag;
    private javax.swing.JTextField TxtfPreco;
    private javax.swing.JTextField TxtfStatus;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem jMIDados;
    private javax.swing.JMenu jMRelatorio;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCodigoContas;
    private javax.swing.JTextField txtfCodigoConta;
    // End of variables declaration//GEN-END:variables
}
