/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Eventos;

import javax.swing.JOptionPane;

/**
 *
 * @author Senac
 */
public class FormEvento extends javax.swing.JFrame {

    /**
     * Creates new form FormEvento2
     */
    public FormEvento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LbEvento = new javax.swing.JLabel();
        TxtfEvento = new javax.swing.JTextField();
        LbData = new javax.swing.JLabel();
        TxtfData = new javax.swing.JTextField();
        LbInicio = new javax.swing.JLabel();
        TxtfInicio = new javax.swing.JTextField();
        LbTermino = new javax.swing.JLabel();
        LbCapacidade = new javax.swing.JLabel();
        TxtfTermino = new javax.swing.JTextField();
        TxtfCapacidade = new javax.swing.JTextField();
        LbLocal = new javax.swing.JLabel();
        LbOrganizador = new javax.swing.JLabel();
        TxtfLocal = new javax.swing.JTextField();
        TxtfOrganizador = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtfDesc = new javax.swing.JTextArea();
        LbDesc = new javax.swing.JLabel();
        LbPublico = new javax.swing.JLabel();
        TxtfPublico = new javax.swing.JTextField();
        BtnLimpar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        lbCodigoEvento = new javax.swing.JLabel();
        txtfCodigoEvento = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMRelatorio = new javax.swing.JMenu();
        jmiDados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        LbEvento.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbEvento.setText("Nome Evento:");

        LbData.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbData.setText("Data:");

        LbInicio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbInicio.setText("Início:");

        TxtfInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtfInicioActionPerformed(evt);
            }
        });

        LbTermino.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbTermino.setText("Término:");

        LbCapacidade.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbCapacidade.setText("Capacidade Máxima:");

        LbLocal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbLocal.setText("Local:");

        LbOrganizador.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbOrganizador.setText("Organizador:");

        TxtfDesc.setColumns(20);
        TxtfDesc.setRows(5);
        jScrollPane1.setViewportView(TxtfDesc);

        LbDesc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbDesc.setText("Descrição:");

        LbPublico.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbPublico.setText("Público alvo:");

        BtnLimpar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BtnLimpar.setText("LIMPAR");
        BtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparActionPerformed(evt);
            }
        });

        btnMostrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnGravar.setText("GRAVAR");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        lbCodigoEvento.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbCodigoEvento.setText("Código:");

        btnAtualizar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbCodigoEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfCodigoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnAtualizar)
                            .addGap(29, 29, 29)
                            .addComponent(btnGravar)
                            .addGap(27, 27, 27)
                            .addComponent(btnMostrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                            .addComponent(BtnLimpar))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(LbOrganizador)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtfOrganizador))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(LbCapacidade)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtfCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(LbPublico)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtfPublico))
                        .addComponent(LbDesc, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(LbLocal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtfLocal))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(LbInicio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtfInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LbTermino)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtfTermino))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(LbEvento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtfEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(LbData)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtfData, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExcluir)
                .addGap(179, 179, 179))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoEvento)
                    .addComponent(txtfCodigoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbEvento)
                    .addComponent(TxtfEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbData)
                    .addComponent(TxtfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbInicio)
                    .addComponent(TxtfInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbTermino)
                    .addComponent(TxtfTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbLocal)
                    .addComponent(TxtfLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LbDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbPublico)
                    .addComponent(TxtfPublico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbCapacidade)
                    .addComponent(TxtfCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbOrganizador)
                    .addComponent(TxtfOrganizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLimpar)
                    .addComponent(btnMostrar)
                    .addComponent(btnGravar)
                    .addComponent(btnAtualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jMRelatorio.setText("Relatório");

        jmiDados.setText("Dados");
        jmiDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDadosActionPerformed(evt);
            }
        });
        jMRelatorio.add(jmiDados);

        jMenuBar1.add(jMRelatorio);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtfInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtfInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtfInicioActionPerformed

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        Limpar();
    }//GEN-LAST:event_BtnLimparActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        Eventos e = this.MontarEventos();
        JOptionPane.showMessageDialog(null,"Nome evento: "+e.getNomeEvento()+"\nData evento: "+e.getDataEvento()+
                "\nHorario início: "+e.getHorarioInicio()+"\nHorario término: "+e.getHorarioTermino()+
                "\nLocal evento: "+e.getLocalEvento()+"\nDescrição: "+e.getDescricao()+"\nPúblico: "+e.getPublico()+
                "\nCapacidade máxima: "+e.getCapacidadeMax()+"\nOrganizador: "+e.getOrganizador());
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        Eventos e = this.MontarEventos();
        if (e != null){
            EventosCtrl ec = new EventosCtrl();
            ec.insert(e);            
        }else{
            JOptionPane.showMessageDialog(null,"Favor preencher todos os campos.");
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        Eventos e = this.MontarEventos();
        if (e != null && !txtfCodigoEvento.getText().trim().isEmpty()){
            e.setCodEventos(Integer.parseInt(txtfCodigoEvento.getText()));
            EventosCtrl ec = new EventosCtrl();
            ec.update(e);
        }else{
            JOptionPane.showMessageDialog(null,"Favor preencher todos os campos.");
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        EventosCtrl ec = new EventosCtrl();
        if (!txtfCodigoEvento.getText().trim().isEmpty()){
            int cod = Integer.parseInt(txtfCodigoEvento.getText());
            ec.delete(cod);
        }else{
            JOptionPane.showMessageDialog(null,"Preencha o campo.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jmiDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDadosActionPerformed
        EventosCtrl ec = new EventosCtrl();
        ec.SelectAll();
    }//GEN-LAST:event_jmiDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public void CadastroEventos() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEvento().setVisible(true);
            }
        });
    }
    
    public Eventos MontarEventos(){
        if (TxtfEvento.getText().trim().isEmpty() || TxtfData.getText().trim().isEmpty()
                || TxtfInicio.getText().trim().isEmpty() || TxtfTermino.getText().trim().isEmpty()
                || TxtfLocal.getText().trim().isEmpty() || TxtfLocal.getText().trim().isEmpty()
                || TxtfDesc.getText().trim().isEmpty() || TxtfPublico.getText().trim().isEmpty()
                || TxtfCapacidade.getText().trim().isEmpty() || TxtfOrganizador.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Favor preencher todos os campos.");
            return null;
        }
        try{
            Eventos e = new Eventos();
            e.setNomeEvento(TxtfEvento.getText());
            e.setDataEvento(TxtfData.getText());
            e.setHorarioInicio(TxtfInicio.getText());
            e.setHorarioTermino(TxtfTermino.getText());
            e.setLocalEvento(TxtfLocal.getText());
            e.setDescricao(TxtfDesc.getText());
            e.setPublico(TxtfPublico.getText());
            e.setCapacidadeMax(Integer.parseInt(TxtfCapacidade.getText()));
            e.setOrganizador(TxtfOrganizador.getText());
            return e;
        }catch(NumberFormatException n){
            JOptionPane.showMessageDialog(null,n,"Error",JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
    
    public void Limpar(){
       txtfCodigoEvento.setText("");
       TxtfCapacidade.setText("");
       TxtfData.setText("");
       TxtfDesc.setText("");
       TxtfEvento.setText("");
       TxtfInicio.setText("");
       TxtfLocal.setText("");
       TxtfOrganizador.setText("");
       TxtfPublico.setText("");
       TxtfTermino.setText("");        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JLabel LbCapacidade;
    private javax.swing.JLabel LbData;
    private javax.swing.JLabel LbDesc;
    private javax.swing.JLabel LbEvento;
    private javax.swing.JLabel LbInicio;
    private javax.swing.JLabel LbLocal;
    private javax.swing.JLabel LbOrganizador;
    private javax.swing.JLabel LbPublico;
    private javax.swing.JLabel LbTermino;
    private javax.swing.JTextField TxtfCapacidade;
    private javax.swing.JTextField TxtfData;
    private javax.swing.JTextArea TxtfDesc;
    private javax.swing.JTextField TxtfEvento;
    private javax.swing.JTextField TxtfInicio;
    private javax.swing.JTextField TxtfLocal;
    private javax.swing.JTextField TxtfOrganizador;
    private javax.swing.JTextField TxtfPublico;
    private javax.swing.JTextField TxtfTermino;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JMenu jMRelatorio;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmiDados;
    private javax.swing.JLabel lbCodigoEvento;
    private javax.swing.JTextField txtfCodigoEvento;
    // End of variables declaration//GEN-END:variables
}
